#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#(npm --no-git-tag-version version patch && git add package.json && yarn run lint:fix && yarn test:unit) || exit 1
#(yarn run lint:fix && yarn test:unit && yarn test:e2e) || exit 1
(yarn run lint:fix && yarn test:unit) || exit 1
