#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'stopped';
exit 1;

#npm --no-git-tag-version version patch;
#PACKAGE_VERSION=$(cat package.json | grep \\\"version\\\" | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]');
#git tag v$PACKAGE_VERSION;
