name: Ship to S3

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Copy .env
        run: cp .env.example .env || echo 'Already exists.'
      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - run: npx browserslist@latest --update-db
      - name: Run Tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test:unit
      - name: Build for production
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build
      - name: Install Dependencies for integration code
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --cwd integration-code
      - name: Build integration code
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build:integration
      - name: Deploy to AWS S3
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'dist/releases'
          destination_dir: ''
